### ISSUE TITLE
Within content search

### ISSUE THREAD

**Issue by AtomicNess123** [mclear-tools/consult-notes#10]
Thanks for this package.
Two questions: 

1. does it search only in the title of the files or also content?
2. If it searches content: does it search two keywords on the same line of anywhere in the file?
Thanks!

**Comment by mclearc** [comment]
So the basic search is for names of files (or if using org-roam, the names of nodes). If you want to search in the content of all notes use `consult-notes-search-in-all-notes`. This uses `consult-grep` or `consult-ripgrep` as its basis. You can set the arguments for grep or ripgrep search with the variables `consult-notes-grep-args` and `consult-notes-ripgrep-args` respectively. Does that clear things up? I can add this all to the README as well.

**Comment by AtomicNess123** [comment]
Ok, so it does basically the same as using rg or ag.
And when it looks within the content with `consult-notes-search-in-all-notes` it doesn't result a file if you search two query terms unless these query terms are in the same line. That is my main question, because I would like to find files containing several query terms in different lines.

**Comment by mclearc** [comment]
Note that ripgrep (and I think ag as well) does do multiline searches. See [this](https://til.hashrocket.com/posts/9zneks2cbv-multiline-matches-with-ripgrep-rg) for example. This works with emacs from the command line but I'm not yet sure whether it will work with consult-ripgrep. Will check on that.

**Comment by AtomicNess123** [comment]
Thanks! I am not sure this is what I need though.

If you notice, the example is as follows:

```shell
$ echo 'apple\norange\nbanana\nkiwi' | rg --multiline '(?s)orange.*kiwi'
orange
banana
kiwi
```
So rg will return everything between orange and kiwi.

However, I am only interested in getting the _filenames_ whose content contain both orange and kiwi, not that they must appear in a certain order and not that I am interested in what there is in between those search terms.

The purpose is to search for documents relevant to a certain topic.

**Comment by mclearc** [comment]
Ok - got it. Have you looked at https://github.com/Wilfred/deadgrep?

**Comment by mclearc** [comment]
At this point I see this as satisfied by `consult-notes-search-in-all-notes` with the `--multiline` option (which is set as default for ripgrep).
