### ISSUE TITLE
Using a variable in consult-notes-sources

### ISSUE THREAD

**Issue by pprevos** [mclear-tools/consult-notes#13]
Hi Colin,

When I use a variable name inside of `consult-notes-sources` I get an error that the content is not a string. I use `denote-directory` from Prot's Denote package, which is a string: `(stringp denote-directory)`.

How can I use variable names in the declaration for `consult-notes-sources`?

Also, could the notes directory be recursive as Denote allows subdirectories?

**Comment by mclearc** [comment]
Hi Peter -- I use a variable in my settings for `consult-notes-sources` like so:

```emacs-lisp
(setq consult-notes-sources
      `(("Zettel"          ?z ,(concat lem-notes-dir "zettel/"))
        ("Lecture Notes"   ?l ,(concat lem-notes-dir "lecture-notes/"))
        ("Reference Notes" ?r ,(concat lem-notes-dir "ref-notes/"))
        ("Org"             ?o "~/Dropbox/org-files/")
        ("Workbook"        ?w ,(concat lem-notes-dir "workbook/"))
        ("Refile"          ?R ,(concat lem-notes-dir "refile-notes/"))))
```
So perhaps the problem is that you haven't used `,` to evaluate the variable in the list? 

As for recursive searches please see issue #12. I also use denote, and as you can see from my sources above I just include every directory I want searched in the sources.

**Comment by pprevos** [comment]
Thanks Colin,

It was also the back-tick before the list that threw me.

Emacs Lisp has many subtleties...

P:)

**Comment by pprevos** [comment]
Thanks Colin,

It was also the back-tick before the list that threw me.

Emacs Lisp has many subtleties...

P:)

**Comment by pprevos** [comment]
Thanks Colin,

It was also the back-tick before the list that threw me.

Emacs Lisp has many subtleties...

P:)
