### ISSUE TITLE
Is it possible to sort denote notes by title in consult-notes-denote-mode?

### ISSUE THREAD

**Issue by nowislewis** [mclear-tools/consult-notes#16]
# Question
Hello, I wonder if there is a way to sort the results by the name of denote titles in the consult's interface?
# main idea
I used a form of recording similar to the card note-taking method, like 1a-computer.org 1b-philosophy.org. The main idea may be seed in the mail list: 
 https://lists.sr.ht/~protesilaos/denote/%3C1C75FF01-EC76-49DF-9AEB-ED718A2795FF%40gmail.com%3E
# Related solution:
Prots provided a very good idea to utilize dired visual mode. It combines "ls" and "sort" to get a buffer and use dired-visual-mode to convert it to a dired mode. But I think the consult-notes interface may do a good job.

I know it might have something to do with the configuration of consult, but I'm not familiar with consult, so I don't know if I should ask a question here.

Thank you very much for your work, it is very useful to cooperate with denote

**Comment by mclearc** [comment]
I'm glad you've found the package helpful. As far as I understand sorting in consult (admittedly, not that far) it does not sort if there has been prior sorting by the completion function. I use vertico, and vertico by default sorts according to history, length, and alphanumeric. You can change this however, so you could do something like `  (setq vertico-sort-function 'vertico-sort-alpha)` and see if that works for you (again, assuming you use vertico). Otherwise I suspect that the dired - eshell hack from Prot is your best bet.

**Comment by nowislewis** [comment]
Thank you for your suggestion! I used vertico and set vertico-sort-function to vertico-sort-alpha. It did sort the results, not by title, but by date or named "denote id":
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/41566630/200641031-638d26ac-3426-4ad6-926e-2e1fe2bb1400.png">
This is not particularly expected, as similar titles can be used to discover the structure.

**Comment by nowislewis** [comment]
It looks like if I remove the id column, everything will work smoothly. I will try it later.

Thank you for the reminder of consult and vertico, and for your nice work!

**Comment by mclearc** [comment]
Glad that works for you -- perhaps it would be worth it to add an option to hide the ID in the display for denote. I'll try and take care of this when I have time.

**Comment by mclearc** [comment]
FYI -- see https://github.com/mclear-tools/consult-notes/commit/92f54a5fe345d390a11acf9008661fe73ae28539

**Comment by nowislewis** [comment]
Great job! Now everything works quite well. 

And vertico-multiform-mode can be used so that alpha sorting only works for consult-notes and does not affect other command sorting
```lisp
 (vertico-multiform-mode)
 (setq vertico-multiform-commands
       '((consult-notes (vertico-sort-function . vertico-sort-alpha))))
 (sets consult-notes-denote-display-id nil)
```
