### ISSUE TITLE
When open some file with consult-notes, buffer-file-name return string with text properties.

### ISSUE THREAD

**Issue by smallzhan** [mclear-tools/consult-notes#17]
Step 1:  (find-file /path/to/notes/note1.org)
now the value of buffer-file-name is "/path/to/notes/note1.org

Step2: with setting /path/to/notes in consult-sources and then `M-x consult-notes' and open note1.org
now buffer-file-name is  something like #("/path/to/notes/note1.org" 0 x (invisible t)) 

I think consult-notes should not affect the `buffer-file-name'

**Comment by mclearc** [comment]
I'm not able to reproduce this. If I open a note via find file and if I open it via consult notes the value of the variable `buffer-file-name` is the same in both cases.

**Comment by smallzhan** [comment]
sorry for the report, I've test with `emacs -Q`, found that the problem is not with consult-notes.   It seems that something is wrong in my config.
