### ISSUE TITLE
Error with "consult-note-sources"

### ISSUE THREAD

**Issue by renbus** [mclear-tools/consult-notes#20]
Hi,

I am using this simple code in order to set up consult-notes, but I get an error when launching the "consult-notes" command. Here is how I install and configure the package:

```
(use-package consult-notes
  :after (consult denote)
  :init (consult-notes-denote-mode 1)
  :config
  (setq consult-notes-sources '("Notes" ?n "~/Documents/Notes")))
```

When I evaluate these lines it seems to be fine. But when I do `M-x consult-notes`, I get the following error:

```
consult-notes--make-all-sources: Wrong type argument: listp, "Notes"
```

The `"Notes"` part do refers to the first argument, because if I enter anything else, let's say "Blah", it will say "Blah" is wrong type argument.

Also, reading the README.md, I though I could even not set the `consult-notes-source` variable, since the `consult-notes-denote-mode` command should set it automatically to `denote-directory`. But it doesn't seem to be the case.

What can I do to get `consult-notes` to work?

Thanks for your time and support.

**Comment by mclearc** [comment]
Thanks for your interest in the package!

> When I evaluate these lines it seems to be fine. But when I do `M-x consult-notes`, I get the following error:
> 
> ```
> consult-notes--make-all-sources: Wrong type argument: listp, "Notes"
> ```

The notes sources var needs to have a list of lists, not strings. So you need something like  `(setq consult-notes-sources '(("Notes" ?n "~/Documents/Notes"))))`

> Also, reading the README.md, I though I could even not set the `consult-notes-source` variable, since the `consult-notes-denote-mode` command should set it automatically to `denote-directory`. But it doesn't seem to be the case.

Ah -- this is because I have a default set, which I will remove. In the meantime you can also just do `(setq consult-notes-sources nil)`

**Comment by renbus** [comment]
Thanks a lot for your quick answer.

You were right about the missing parenthesis, but then I still had some
trouble getting the "consult-notes" command to work. To have it working I
had to set the "consult-notes-sources", but also
"consult-notes--all-sources" and "consult-notes-denotes--sources" variables
to nil, because they were filled with a bunch of my previous attempts at
getting this to work. I guess this is a common pitfall in Elisp; I am new
at configuring Emacs...

In the end, I simply use:

```
(use-package consult-notes
  :after (consult denote)
  :config
  (setq consult-notes-use-rg t)
  (consult-notes-denote-mode 1))
```

And it seems to be working great. Thanks again for your quick answer.

Le lun. 28 nov. 2022, à 17 h 00, Colin McLear ***@***.***> a
écrit :
