### ISSUE TITLE
Can't create denote notes by consult candidate

### ISSUE THREAD

**Issue by hsingko** [mclear-tools/consult-notes#21]
I believe it is due to a mistake here: 
https://github.com/mclear-tools/consult-notes/blob/bfcc6b8e077cb0056b0cbd5cd602e61e4c0dad10/consult-notes-denote.el#L116

`directory` should be `subdirectory`

**Comment by mclearc** [comment]
Thanks! see https://github.com/mclear-tools/consult-notes/commit/6e8299d4e53b758985a228c296aeb851440fa01a
