### ISSUE TITLE
Is it possible to filter denote subdirectory like normal note source but remain denote display style?

### ISSUE THREAD

**Issue by hsingko** [mclear-tools/consult-notes#24]
As far as I know, there are two ways to add denote notes:
1. add denote directory just like normal notes
    + I can filter notes by prefix  ?key ,  and search notes in sub-directory by custom name
    + But lack of denote display style, keyword highlight, title etc.
2. turn on the `consult-notes-denote-mode`, automatically import all denote notes including sub-directory
    + notes in sub-directory is searchable and with special styles
    + But can't search and filter sub-directory notes by  `name` like normal notes

I tried to combine both methods, manually add denote sub-directory like this, and turn on denote mode at the same time:
```elisp
  (setq consult-notes-sources '(
                                ("Casts"  ?c  "~/Documents/org/casts")  ;normal notes
				("Posts" ?p "~/Documents/org/notes/posts") ; notes/posts is sub-directory of denote directory notes/
                                )) ;; Set notes dir(s), see belo
```

It worked as I excepted, but produced duplicate candidates:
![image](https://user-images.githubusercontent.com/74039541/207076283-8d426833-299e-46ba-8db9-ca9e07ca1652.png)

Is there a more elegant way to do this?

**Comment by mclearc** [comment]
I've updated the `consult-notes-denote-mode` function so that it can (optionally) display the subdirectory name as a searchable part of the display (much like the keyword or title, etc). See the customize group options and the commit here: https://github.com/mclear-tools/consult-notes/commit/c2fa07e60bce0bdb2c58bdbb9367f790428779fe

**Comment by hsingko** [comment]
Great work! That's exactly what I want.
