### ISSUE TITLE
Filter candidates fails if search pattern occurs in directory path

### ISSUE THREAD

**Issue by hsingko** [mclear-tools/consult-notes#25]
Suppose I have these note source:
```elisp
(setq consult-notes-sources
      '(("Org"             ?o "~/Dropbox/org-files")
        ("Org Refile"      ?r "~/Dropbox/Work/projects/notebook/org-refile")))
```
Patterns like `D`,`Drop`, `Dropbox` etc won't filter candidates.

This problem caused by below code:
https://github.com/mclear-tools/consult-notes/blob/da0cd4105fcba365375cba45aa80d293969231fa/consult-notes.el#L182

Although the `dir` is invisible, it can still be searched by `consult`, but it's invisible to user, so it looks like nothing happened. It will be a problem if note title contains those pattern, say, `2022-messagebox.org`

I noticed that `consult-notes-denote` handles this situation differently, `dir` is put into text-property, maybe `consult-note` should do similar thing?

**Comment by mclearc** [comment]
If you pull the most recent version I've cleaned this up so the path gets listed with the annotations. This still allows narrowing with the relevant `char` but there is no longer an invisible text property that might mess things up. See commit https://github.com/mclear-tools/consult-notes/commit/3f0947f22715ad9344797d382986e1b46d81c07d (note that some variables names have changed).

**Comment by hsingko** [comment]
@mclearc 
btw, I think there's a mistake in `README.org`:
```elisp
  :config
  (setq consult-notes-file-dir-sources '("Name"  ?key  "path/to/dir")) ;; Set notes dir(s), see below
```
`consult-notes-file-dir-sources` should be a list
