### ISSUE TITLE
Wrong type argument

### ISSUE THREAD

**Issue by svnsbck** [mclear-tools/consult-notes#26]
Hi!
I'm not quite sure which package-update caused this but invoking consult-notes returns this error since this morning:

`Error in post-command-hook (vertico--exhibit): (wrong-type-argument number-or-marker-p `nil)``

I haven't changed anything in my config I believe.  Is there anything that I can do about this?

**Comment by mclearc** [comment]
I haven't been able to reproduce this. But I did change the names of several variables (though they should be aliased to the old variables). Perhaps review the setup in the README and see if you can narrow down the problem?

**Comment by sthesing** [comment]
I observe the same behaviour.
It seems to be related to `consult-notes-file-dir-sources`.

I use consult-notes with denote. If I set it up like this, I get the above mentioned Error.
```
  (consult-notes-denote-mode)
  (setq consult-notes-file-dir-sources
         `(("Zettels"  ?z ,denote-directory)
           ("Excerpts" ?e "~/Documents/denote-zk/excerpts")))
```
Turning off `consult-notes-denote-mode` doesn't change this.
However, if I comment out the last three lines, `consult-notes` comes up normally. Just my narrowing keys are gone, of course. 

Does that help?

**Comment by mclearc** [comment]
@sthesing Unfortunately I'm still unable to reproduce this error. I've tried it both with my config and using default `emacs -q`. Is consult and whatever the rest of your stack is (e.g. vertico, orderless, etc.) up to date? Would it be possible for you or @svnsbck to turn on debug (e.g. `M-x toggle-debug-on-error`) and tell me what the stack trace is? Please also let me know what your emacs version is.

**Comment by mclearc** [comment]
You might also pull the latest changes for the package -- I don't expect that I've fixed the error but worth checking in any case.

**Comment by sthesing** [comment]
I use Emacs 28.2, here are the versions of the packages that might be interesting. If any are missing that you want to know about, just say the word.

| package               |       version |
|-----------------------|---------------|
| cape                  |          0.11 |
| consult               | 20221211.1019 |
| consult-dir           |           0.1 |
| consult-notes         | 20221216.1540 |
| consult-project-extra |           0.1 |
| corfu                 |          0.34 |
| corfu-terminal        |           0.5 |
| embark                | 20221208.1524 |
| embark-consult        |           0.6 |
| marginalia            |  20221206.147 |
| orderless             | 20221128.2330 |
| vertico               |          0.29 |

I tried `toggle-debug-on-error` but I don't see any output, just the error message in the mini-buffer. Any idea how to see the debugger's output? I sadly have no experience debugging elisp code.

**Comment by svnsbck** [comment]
Hi!  Sorry for the late reply, long day at work.

I have turned on debugging but the output is the same:

`Debug on Error enabled globally
Error in post-command-hook (vertico--exhibit): (wrong-type-argument number-or-marker-p nil)
`
I also have tried the Melpa version as well as cloned the repository with the same result.  Another slightly strange behaviour is, that if I C-g out of the minibuffer (once the error ocurred) a Dired buffer with the first folder in my list opens, and when I bury that, the second one as well.  

I run emacs 28.1, consult 20221211.1019, marginalia 20221206.147,  orderless 20221128.2330, and vertigo 0.29, in fact the same at @sthesing

**Comment by mclearc** [comment]
So -- running the latest version of consult-notes (commit https://github.com/mclear-tools/consult-notes/commit/5cb24d8202795fc380fe173ecad31f7c969320fd) I can't reproduce the problem (though I did fix the bug @svnsbck mentions concerns dired buffers). I've tried on both emacs 28.2 and 29, but I don't think it should be an issue for either version or even emacs 27. With the latest updates can you reproduce the issue with emacs -Q and just the basic settings?

**Comment by mclearc** [comment]
Here's an example to evaluate in the scratch buffer from a vanilla (i.e. `emacs -Q`) setup:

```emacs-lisp
(package-initialize)
(package-install 'vertico)
(package-install 'orderless) 
(package-install 'consult)
(package-install 'consult-notes)
(package-install 'denote)

(setq notes-dir "/path-to-/notes/")
(customize-set-variable 'denote-directory notes-dir)

(require 'denote)
;;;; Consult Notes
;; (consult-notes-denote-mode)
(setq consult-notes-file-dir-sources
      `(("Zettel"          ?z ,(concat notes-dir "zettel/")))

```

though for this to work you'd have to wait for melpa to pull the latest changes. Alternatively pull the repo from git hub and add it to your load-path in the scratch buffer like so: `(push "path/to/consult-notes/" load-path)`

**Comment by svnsbck** [comment]
I have found the bug.  The solution had been in the `forward-slash`.

My setup looked like the one in readme as for example:

     (setq consult-notes-file-dir-sources
          '(("Org"             ?o "~/Dropbox/org-files")
           ("Org Refile"      ?r "~/Dropbox/Work/projects/notebook/org-refile")))

I noticed though that your snippet above, had the `forward-slash` ending the folder title.  Adding this fixed it.  I don't know what caused that, since it had been working without that for quite some time.  I can reproduce the error reliably by adding/removing the forward-slash.  I also pulled in the latest version of the package though.

**Comment by mclearc** [comment]
Excellent! And predictably I had the trailing slash in my setup. But once I removed it I could reproduce the error. I suspect the difference comes in the way I have retooled the functions for consult-notes, so that file previews are possible. I'm sorry for the the problems this caused, but glad you figured it out!

**Comment by sthesing** [comment]
Adding trailing slashes to the paths fixes the issue for me, too.

Thanks for the detective work, @mclearc and @svnsbck !
