### ISSUE TITLE
Retaining case in denote's note titles

### ISSUE THREAD

**Issue by krisbalintona** [mclear-tools/consult-notes#27]
Currently, `consult-notes-denote--source` presents titles that do not maintain the casing of the actual title of notes. This is because `denote-retrieve-filename-title` is used, which only desluggifies the note name (i.e. all but the first character is lowercased).

What should be used instead is `denote-retrieve-title-value`. So in `consult-notes-denote--source`, I would use `(denote-retrieve-title-value f (denote-filetype-heuristics f))` instead of `(denote-retrieve-filename-title f)` where applicable.

Before:
![image](https://user-images.githubusercontent.com/82680088/209225647-04c2f3f1-326a-4f57-aa1c-ed9086b30311.png)

After:
![image](https://user-images.githubusercontent.com/82680088/209225596-52309ee0-a466-48fd-bebc-b7de35c69c0f.png)

**Comment by mclearc** [comment]
Great -- thanks! I'll push a fix for this in a few minutes
