### ISSUE TITLE
`void-variable consult-notes-org-headings-files`  in `consult-notes-search-in-all-notes`

### ISSUE THREAD

**Issue by Croissong** [mclear-tools/consult-notes#28]
With the latest changes from 6aef8b523, `consult-notes-search-in-all-notes` fails with
```emacs-lisp
Debugger entered--Lisp error: (void-variable consult-notes-org-headings-files)
  consult-notes-search-in-all-notes()
```
if *consult-notes-org-headings.el* has not been loaded and `consult-notes-org-headings-files` hasn't been initialized manually.
Minimal example:
```emacs-lisp
(use-package consult-notes)
(consult-notes-search-in-all-notes)
```

**Comment by mclearc** [comment]
Thanks! Should be fixed now.
