### ISSUE TITLE
consult--display-width: Symbol’s function definition is void: compat-string-widt

### ISSUE THREAD

**Issue by IceAsteroid** [mclear-tools/consult-notes#31]
Emacs cannot launch consult-notes but results in an error prompt: "consult--display-width: Symbol’s function definition is void: compat-string-widt"

Here's my config file: https://pastebin.com/WHrknfaW

Emacs version: GNU Emacs 29.0.50

**Comment by IceAsteroid** [comment]
Should I post my configuration here instead?

**Comment by mclearc** [comment]
This isn't a consult-notes issue as far as I can tell. Looks like there is a typo in `consult--display-width`. I suspect you should update consult and its dependencies.

**Comment by IceAsteroid** [comment]
@mclearc Yeah, after I tried to remove all the packages and to reinstall again, the problem was magically solved.
