### ISSUE TITLE
Error when using consult-notes from denote SILO

### ISSUE THREAD

**Issue by morgandavidson** [mclear-tools/consult-notes#32]
I use denote on Emacs 28.2.

```
(use-package denote
  :hook (dired-mode . denote-dired-mode)
  :custom (denote-directory pkb-path (denote-file-type 'org))
  )
```

I have set two directory sources:
```
(use-package consult-notes
  :commands (consult-notes
               consult-notes-search-in-all-notes)
  :config
  (setq consult-notes-file-dir-sources `(("PKB"  ?k  ,pkb-path)
					   ("MT" ?t ,(concat mandates-path "MandateTest"))))  
  (when (locate-library "denote")
    (consult-notes-denote-mode))
  :bind ("C-c d f" . consult-notes)
    )
```
In your documentation, you say:

>  To narrow to a particular source, use its designated narrowing key.

How is this done?

Also, when I'm in a note from `MandateTest` directory `consult-notes` doesn't work. I have the following error message: `file-relative-name: Wrong type argument: stringp, default-directory`

**Comment by mclearc** [comment]
So I am unsure why you're seeing the latter error about default-directory. Have you tried a backtrace? As for configuration, you seem to be doing everything right. For example this is what I have. 

```emacs-lisp
;; Consult Notes Setup
(with-eval-after-load 'consult-notes
  (setq consult-notes-file-dir-sources
        `(("Agenda Files" ?a ,(car org-agenda-files))
          ("Refile Notes" ?r ,(concat lem-notes-dir "refile-notes/")))))
``

**Comment by morgandavidson** [comment]
I found the solution for narrowing: `<` has to be input before the designated narrowing key. Maybe you could update documentation as follows:

> To narrow to a particular source, press `<` then use its designated narrowing key.

Regarding the `consult-notes` error, adding `with-eval-after-load 'consult-notes` didn't change anything.

What does backtrace means, and how can I backtrace?

**Comment by mclearc** [comment]
> I found the solution for narrowing: `<` has to be input before the designated narrowing key (since I have `(setq consult-narrow-key "<")` in my init). Maybe you could update documentation as follows:

You shouldn't need to do this to narrow. This is likely something you have set in consult. Consult-notes is going to defer to whatever your general consult settings are. 

> Regarding the `consult-notes` error, adding `with-eval-after-load 'consult-notes` didn't change anything.

No, it wasn't intended to. That was just to show that i have a similar configuration set and it works fine. 

> What does backtrace mean ? And how can I backtrace?

See here (or the corresponding info node in Emacs): https://www.gnu.org/software/emacs/manual/html_node/elisp/Backtraces.html

> Note that MandateTest is a Silo:
> 
> ```
>   (defvar my-denote-pick-silo-then-command
>       `(,(concat mandates-path "MandateTest/")))
>   (defvar my-denote-commands-for-silos '(denote))
> 
>   (defun mda/denote-silos (silo command)
>     (interactive
>      (list (completing-read "Select a silo: " my-denote-pick-silo-then-command nil t)
> 	   (intern (completing-read
> 		    my-denote-commands-for-silos nil t))))
>     (let ((denote-directory silo))
>       (call-interactively command)))
> ```

Can you reproduce your problem with `Emacs -q`? What about with a non-siloed denote directory?

**Comment by morgandavidson** [comment]
The issue only occurs when the buffer is reading a file from SILO or when dired is in SILO.

Here is a minimal 28.2 init reproducing the bug with `emacs -q`:


```
;; =SyncA3= and =SyncSW= paths

(setq
 SyncA3-path "~/SyncA3/"
 SyncSW-path "~/SyncSW/"
 )

;; Other directories

(setq
					; SyncA3
 orgmode-path (concat SyncA3-path "Mementos/Org-Mode/")
 references-path (concat orgmode-path "References/")
 pkb-path (concat references-path "KB")
					; SyncSW
 orgmode-sw-path (concat SyncSW-path "Mementos/Org-Mode/")
 references-sw-path (concat orgmode-sw-path "References/")
 mandates-path (concat references-sw-path "Work/Mandates/")
 )

;; Emacs Package Repositories

(require 'package)
(setq package-archives
   '(("melpa" . "https://melpa.org/packages/")
     ("elp" . "https://elpa.gnu.org/packages/")
     ("gnu-devel" . "https://elpa.gnu.org/devel/")
     ("nongnu" . "https://elpa.nongnu.org/nongnu/")
     ))

;; Activate use-package

(require 'package)
(package-initialize)
(require 'use-package)

;; Package installation
;; - Auto install all packages called by =use-package=

(require 'use-package-ensure)
(setq use-package-always-ensure t)

;; Package update
;; - Keep packages called by =use-package= automatically updated

(use-package auto-package-update
  :config
  (setq auto-package-update-delete-old-versions t)
  (setq auto-package-update-hide-results t)
  (auto-package-update-maybe))

;; Emacs
;; - =vertico= (VERTical Interactive COmpletion)

(use-package vertico
  :custom 
  (vertico-cycle t)
  :init
  (vertico-mode))


;; - Savehist mode saves minibuffer histories

(use-package savehist
  :init
  (savehist-mode))

;; =deadgrep= [SIN]

(use-package deadgrep)

;; =orderless=

(use-package orderless
  :custom (completion-styles '(orderless)))

;; =consult=

(use-package consult
  :bind (;; M-s bindings (search-map)
	 ("C-f" . consult-line)
	 ("M-s f" . consult-find)
	 ("M-s g" . consult-grep)
	 ("M-s l" . consult-line)
	 ("M-s L" . consult-line-multi)
	 ("M-s k" . consult-keep-lines)
	 ("M-s r" . consult-ripgrep)
	 ("M-s u" . consult-focus-lines))
  :config (setq consult-narrow-key "<") ;; "C-+"
  )

;; =use-package= config

(use-package denote
  :hook (dired-mode . denote-dired-mode)
  ;:custom (denote-directory pkb-path (denote-file-type 'org))
  :config
  (setq denote-directory pkb-path
	denote-file-type 'org
	xref-search-program 'ripgrep
	)
  :bind
  ("C-c d b" . 'denote-org-dblock-insert-backlinks)
  ("C-c d B" . 'denote-link-find-backlink)
  ("C-c d d" . 'denote)
  ("C-c d c" . 'denote-open-or-create)
  ("C-c d k" . 'denote-keywords-add)    ;; update file name automatically
  ("C-c d K" . 'denote-keywords-remove) ;; update file name automatically
  ("C-c d l" . 'denote-link)
  ("C-c d r" . 'denote-rename-file-using-front-matter)
  ("C-c d s" . 'mda/denote-silos)
  ("C-c d t" . 'denote-org-dblock-insert-links)
  )

;; Specify silos directories

(defvar my-denote-pick-silo-then-command
  `(,(concat mandates-path "MandateTest/")
    ;; You don't actually need to include the `denote-directory' here
    ;; if you use the regular commands in their global context.  I am
    ;; including it for completeness.
    ;;,denote-directory
    )
  "List of file paths pointing to my Denote silos.
This is a list of strings.")

;; Silos' =denote= commands

(defvar my-denote-commands-for-silos
  '(denote
    ;denote-template
    )
  "List of Denote commands to call after selecting a silo.
This is a list of symbols that specify the note-creating
interactive functions that Denote provides.")

;; Silo command

(defun mda/denote-silos (silo command)
  "Select SILO and run Denote COMMAND in it.
SILO is a file path from `my-denote-pick-silo-then-command', while
COMMAND is one among `my-denote-commands-for-silos'."
  (interactive
   (list (completing-read "Select a silo: " my-denote-pick-silo-then-command nil t)
	 (intern (completing-read
		  "Run command in silo: "
		  my-denote-commands-for-silos nil t))))
  (let ((denote-directory silo))
    (call-interactively command)))

;; Use =consult-notes= to search notes from knowledge base

(use-package consult-notes
  :commands (consult-notes
	     consult-notes-search-in-all-notes)
  :config
  (with-eval-after-load 'consult-notes
    (setq consult-notes-file-dir-sources `(("PKB"  ?k  ,pkb-path)
					   ("MT" ?t ,(concat mandates-path "MandateTest")))))
  (when (locate-library "denote")
    (consult-notes-denote-mode))
  :bind ("C-c d f" . consult-notes)
  )
```

**Comment by mclearc** [comment]
The problem with denote silos is that the suggested .dir-locals.el file assumes you just want to set the `denote-directory` local dir to the value of `default-directory`. But the consult-notes function for denote assumes that the value of `denote-directory` is a string and not a variable (that needs to be evaluated) or a symbol. 

Rather than muck about with my code for what is somewhat of an edge case, the easiest thing to do is to set the value of `denote-directory`	in the .dir-locals.el file to a string path. So something like:

```emacs-lisp
((nil . ((denote-directory . "~/Documents/notes/test-silo/"))))
```
If you do that then when using consult-notes in that dir, you should only see the notes in that dir as part of your denote notes (and there should be no error thrown). 

Let me know if that works for you.

**Comment by morgandavidson** [comment]
Thank you, I put `((nil . ((denote-directory . "./"))))` in `.dir-locals.el` instead of `((nil . ((denote-directory . default-directory))))`, and now it works fine.

Maybe you could add some warning about SILO in your documentation or ask Prot to amend his.
