### ISSUE TITLE
consult-notes-search-in-all-notes does not uses consult-notes-file-dir-sources

### ISSUE THREAD

**Issue by weirdvic** [mclear-tools/consult-notes#38]
Hello, this is my init.el config for consult-notes with org-roam as the only source:

```elisp
(use-package consult-notes
  :commands (consult-notes
             consult-notes-search-in-all-notes
             consult-notes-org-roam-find-node
             consult-notes-org-roam-find-node-relation)
  :config
  (setq consult-notes-file-dir-sources '(("org-roam"  ?n "~/org-roam")))
  (consult-notes-org-roam-mode)
  :bind
  ("C-c n r" . consult-notes-search-in-all-notes))
```

It is pretty basic almost no changes from the sample config in the README.

The problem is in invoking `consult-notes-search-in-all-notes`. It seems that ripgrep takes current buffer's directory as the starting point instead searching in `consult-notes-file-dir-sources`. For example: when I have note buffer on my screen and hit `C-c n r`, ripgrep starts at the note folder: `~/org-roam` and this is fine. But if I try to search in notes from any other buffer, ripgrep searches in that buffer's directory.

Is there a way to invoke `consult-notes-search-in-all-notes` from any buffer?

**Comment by mclearc** [comment]
I'm not sure what the problem is here since this works fine on my end. The search should run just with respect to your notes dir. Are you using grep or ripgrep? Are you using any odd arguments or did you change any of the args in `consult-notes-ripgrep-args`? What's your emacs version? Are you on windows or mac or linux?

**Comment by weirdvic** [comment]
Nevermind, probably my config was messed up, now all good.

**Comment by darosio** [comment]
> Nevermind, probably my config was messed up, now all good
Where your config was messed up? I am experiencing very similar problem.
thanks
