### ISSUE TITLE
is `consult-notes` with `denote` broken?

### ISSUE THREAD

**Issue by JonatanSahar** [mclear-tools/consult-notes#40]
it used to work, but after a recent update of my packages I get:

> Invalid function: ("c:/Users/Jonathan/notes/20230323T111555--paper-summaries-from-guy__thesis.org" "c:/Users/Jonathan/notes/20230323T113003--knowledge-base__thesis.org" "c:/Users/Jonathan/notes/20230323T113249--action-modulates-perception__thesis.org" "c:/Users/Jonathan/notes/20230323T113609--action-modulates-preparatory-sensory-neural-activity__thesis.org" "c:/Users/Jonathan/notes/20230323T113638--action-sensory-modulation-is-learning-based__thesis.org" "c:/Users/Jonathan/notes/20230329T113432--stronger-modulation-in-ipsilateral-configuration__thesis.org" "c:/Users/Jonathan/notes/20230329T121953--enhanced-auditory-evoked-activity-to-self-generated-sounds-reznik-et-al__bib_thesis.org" "c:/Users/Jonathan/notes/20230329T135029--advantage-in-contralateral-configuration__thesis.org" "c:/Users/Jonathan/notes/20230329T155402--thesis-draft__thesis.org" "c:/Users/Jonathan/notes/20230331T070538--איך-לבחור-מניות__finance.org" ...)

Thanks!

**Comment by mclearc** [comment]
I haven't made any changes to consult-notes in the last couple months. The last commit was april 18th. Is it possible there is another package causing trouble? You might see when the last time was you had updated and roll back to that version of consult-notes and see if things work.

**Comment by JonatanSahar** [comment]
I was thinking denote was changed and broke the integration actually.

**Comment by mclearc** [comment]
Hard to say. I don't see any breaking changes over at the denote repo. Though there has been an update in the docs there concerning [siloed directories](https://protesilaos.com/emacs/denote#h:15719799-a5ff-4e9a-9f10-4ca03ef8f6c5). Not sure if that is pertinent for you.

**Comment by JonatanSahar** [comment]
Seems to work now.. some emacs voodo I guess ::shrug::
