### ISSUE TITLE
make most recently creates note first in completion minibuffer

### ISSUE THREAD

**Issue by JonatanSahar** [mclear-tools/consult-notes#41]
when creating new notes, either through `consult-notes` or through `denote` itself, the created files are not considered as most recently changed in the sorting of the list of notes - although they're often what one would want to access most.

**Comment by mclearc** [comment]
This is beyond the scope of consult-notes. You should use a completion system that sorts for recent or frequently used files ("recency"). For example (presuming you're using vertico for completion), you should look at the value of `vertico-sort-function`.
