### ISSUE TITLE
does the denote minor mode actually set consult-notes-file-dir-source? i don't see this anywhere

### ISSUE THREAD

**Issue by gitrj95** [mclear-tools/consult-notes#43]
oh, looks like my confusion is solved here: 

```
                  (when (bound-and-true-p consult-notes-denote-mode)
                    (concat (expand-file-name denote-directory) " "))
```
the issue i'm running into is that consult-notes-search-in-all-notes always appears to set dir to the cwd, instead of using the dir set in denote-directory

**Comment by gitrj95** [comment]
oh, looks like it's set here: 

```
                  (when (bound-and-true-p consult-notes-denote-mode)
                    (concat (expand-file-name denote-directory) " "))
```
the issue i'm running into is that consult-notes-search-in-all-notes always appear to set dir to the cwd, instead of using the dir set in denote-directory

**Comment by gitrj95** [comment]
the denote directory also always appears to be "./"
<img width="816" alt="Screenshot 2023-06-28 at 11 15 11 PM" src="https://github.com/mclear-tools/consult-notes/assets/68976909/1bda3071-f9ab-4ab4-be75-2d74b069b86e">

**Comment by gitrj95** [comment]
wrt the latter: looks like it takes the relative dir by design. this isn't that intuitive to me, personally

**Comment by gitrj95** [comment]
the former seems to be related to the way consult-ripgrep and consult-grep are called in the function? is that correct?

**Comment by mclearc** [comment]
Thanks. This has been an issue in the past, and I guess is so again. I've opened an issue upstream (see https://github.com/minad/consult/issues/818).

**Comment by gitrj95** [comment]
the new semantics should simplify your code a bit. looks like it's all been corrected now. thanks
