### ISSUE TITLE
Embark integration from documentation not working

### ISSUE THREAD

**Issue by MarcRohrer** [mclear-tools/consult-notes#46]
Hi,

the functions from the documentation for Embark integration don't seem to work:

```
(defun consult-notes-grep (cand)
  "Run grep in directory of notes file CAND."
  (interactive "fNote: ")
  (consult-grep (file-name-directory cand)))
``` 
"cand" does not look like a filename, it is merely the text of the line Embark is called from.
Is there a way to get the filename?

I want to create a function that appends the content various denotes to a buffer.

Marc

**Comment by mclearc** [comment]
Thanks for this question. I haven't really kept up with embark and the function as I've revised consult-notes. So I'm going to take most of these examples down. As for what you want, it sounds like you should use something like `(denote-get-path-by-id (car (split-string (format "%s" cand))))` to get the full path to the file under point and then append it to a temp buffer, or collect the file path, or whatever it is you want to do with it.

**Comment by MarcRohrer** [comment]
thanx for the info!

Marc
