### ISSUE TITLE
Enable future history with consult-notes

### ISSUE THREAD

**Issue by hmelman** [mclear-tools/consult-notes#49]
I've just added this to the `consult--multi` call in my version of`consult-notes`.  It enables future history on the command, so hitting `M-n` will set the input as `symbol-at-point` or region if it's set.

```elisp
:add-history (seq-some #'thing-at-point '(region symbol)) ; future history
```

**Comment by mclearc** [comment]
Thanks! Added in https://github.com/mclear-tools/consult-notes/commit/eb4c59b8a43c5b74250f92cf8eb05c659efb04d0
