### ISSUE TITLE
Add org-ql search capability 

### ISSUE THREAD

**Issue by mclearc** [mclear-tools/consult-notes#5]
See https://github.com/alphapapa/org-ql via https://www.reddit.com/r/emacs/comments/v7h6jk/comment/ibm8slm/?utm_source=share&utm_medium=web2x&context=3

**Comment by EFLS** [comment]
One thing to note: The Org-ql search opens each file in its search path. With hundreds of notes, this becomes quite a time and resource intensive process. (I've used it to collect Org-journal notes.)

**Comment by mclearc** [comment]
Given the point made by EFLS I think this won't be added any time in the forseeable future.
