### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (wrong-type-argument number-or-marker-p nil) 

### ISSUE THREAD

**Issue by cnoceda** [mclear-tools/consult-notes#50]
Hi, 
yesterday I was getting this error when I execute `consult-notes`. After some investigation I found the problem in `consult-notes-org-headings-annotations`.
This line ` (fsize (file-size-human-readable (file-attribute-size attrs))))` when try to read the headers, `attrs` become nil and crash. I' ve solved whit ` (fsize (file-size-human-readable (or (file-attribute-size attrs) 0 ))))`, but i dont know if it's the best way to do it or it's a problem of my configuration. 

I hope it's useful.

Regards.

**Comment by mclearc** [comment]
Hmm -- I haven't noticed any problem. Could you tell me what version of Vertico and Consult you are using? It's possible that there's been a change in one or both of those that will require me to do different error handling.

**Comment by cnoceda** [comment]
Hi, those are my versions:

- vertico 1.4
- Consult 20231006.1423
- consult-notes 20231027.1436  

The error throw when try to get the headers section, with notes or files works perfect. 
And by the way, thanks for the pice of code it's very helpful :-)
Regards,
