### ISSUE TITLE
Consider named or basic faces instead of using Consult's own

### ISSUE THREAD

**Issue by protesilaos** [mclear-tools/consult-notes#6]
Hello Colin,

I noticed the faces in this:

```elisp
(defun consult-notes-annotate-note (name cand)
  "Annotate file CAND with its source NAME, size, and modification
time."
  (let* ((attrs (file-attributes cand))
         (fsize (file-size-human-readable (file-attribute-size attrs)))
         (ftime (consult-notes--time (file-attribute-modification-time attrs))))
    (put-text-property 0 (length name)  'face 'consult-separator name)
    (put-text-property 0 (length fsize) 'face 'consult-key fsize)
    (put-text-property 0 (length ftime) 'face 'consult-key ftime)
    (format "%s  %5s  %5s" name fsize ftime)))
```

The resulting presentation can be problematic in two ways:

1. `consult-key` is used for key bindings.  Some user/theme may style
   those in a pseudo-physical-key fashion, just as current Emacs master
   does for generic key bindings (e.g. `C-h C-h`).  More broadly, an
   aesthetic for keybindings may not be suitable for the information you
   provide there.

2. The `consult-separator` is supposed to style a thin line/border.
   This has different requirements than colourising text.  A border that
   stretches from one side of the screen to the other can afford a very
   faint grey value, but text needs to be more legible.

Maybe you can use `defface` to provide your own faces?  They may inherit
from the aforementioned, if you want.

Or, you can use basic faces from `M-x find-library RET faces RET` like
`shadow` and `bold`:

```elisp
(defun consult-notes-annotate-note (name cand)
  "Annotate file CAND with its source NAME, size, and modification
time."
  (let* ((attrs (file-attributes cand))
         (fsize (file-size-human-readable (file-attribute-size attrs)))
         (ftime (consult-notes--time (file-attribute-modification-time attrs))))
    (put-text-property 0 (length name)  'face 'shadow name)
    (put-text-property 0 (length fsize) 'face 'bold fsize)
    (put-text-property 0 (length ftime) 'face 'bold ftime)
    (format "%s  %5s  %5s" name fsize ftime)))
```

Replace `bold` with `success`, `error`, `warning` for some added
colouration:

```elisp
(defun consult-notes-annotate-note (name cand)
  "Annotate file CAND with its source NAME, size, and modification
time."
  (let* ((attrs (file-attributes cand))
         (fsize (file-size-human-readable (file-attribute-size attrs)))
         (ftime (consult-notes--time (file-attribute-modification-time attrs))))
    (put-text-property 0 (length name)  'face 'shadow name)
    (put-text-property 0 (length fsize) 'face 'warning fsize)
    (put-text-property 0 (length ftime) 'face 'success ftime)
    (format "%s  %5s  %5s" name fsize ftime)))
```

Thanks!

**Comment by mclearc** [comment]
Thanks Protesilaos -- these are all good suggestions. I'll define some faces accordingly.

**Comment by protesilaos** [comment]
Thank you!
