### ISSUE TITLE
Consult-node-demote mode preview issues

### ISSUE THREAD

**Issue by pprevos** [mclear-tools/consult-notes#61]
Hi,

I have associated certain file types with external software, e.g. Denote files in MP4 format (Denote can be used for any type of file):

```
(use-package openwith
  :config
  (openwith-mode t)
  :custom
  (openwith-association 
    '(("mp4" "vlc" (file)))))
```

In consult I have excluded these files from the preview:

```
(setq consult-preview-excluded-files '("mp4$"))
```

When I configure `consult-notes` to view a directory, consult will not preview the excluded files, as configured. However, when enabling `consult-notes-denote-mode` the excluded files are previewed and the external software pops up as soon as I hit an MP4 file.

Can the code be upgraded so that excluded preview files are recognised?

Peter

**Comment by mclearc** [comment]
Hi @pprevos -- Thanks for this report. Could you try the possible fix I implemented [on this branch](https://github.com/mclear-tools/consult-notes/tree/preview-exclude) and let me know if that resolves the problem?

**Comment by pprevos** [comment]
Hi Colin, this works great. Thanks for maintaining this package - I use it a lot.

**Comment by mclearc** [comment]
Glad to hear it! Closed by https://github.com/mclear-tools/consult-notes/commit/c97420c8e91aaae214be7de897eb7eb9b7843520
