### ISSUE TITLE
Search multiples tags wit denote

### ISSUE THREAD

**Issue by apraga** [mclear-tools/consult-notes#66]
Hi, 

Just discovered denote and your package that is super helpful to find notes. One find that I could not find is how to search for multiple tags. Ony the first seems to be used 

![image](https://github.com/user-attachments/assets/cb2dbed3-12d4-4023-81f8-19a1c846b678)

Denote tags syntax is #filetags: :tag1:tag2: Thanks !

**Comment by leafarbelm** [comment]
Check out issue #37

**Comment by apraga** [comment]
Indeed, thanks for tip (I did not find the issue) ! I'll make a PR to update the documenation if that's okay with you.
