### ISSUE TITLE
How to open multiple notes?

### ISSUE THREAD

**Issue by morgandavidson** [mclear-tools/consult-notes#71]
I'm using consult-notes to search/open denote notes, and I'm very happy with it, thank you very much for this great package.

There is functionality that I would find useful. I wonder if it exists. If yes how to use it, if not, would it be possible to implement it?

Here is the use case: 

I type `plato` in `consult-notes`, then 3 results appear (because I have 3 notes tagged with `plato`). I'd like to be able to open the 3 notes, each one in a buffer.

**Comment by mclearc** [comment]
Hi @morgandavidson -- Sorry for the very delayed response. Consult-notes doesn't provide this functionality, but [Embark](https://github.com/oantolin/embark) does. You would run consult-notes, perform your search, use embark-select on all buffers you'd like to open, and then use embark-act-all to open those selected buffers. 

More generally, Embark is a great package, especially as part of the vertico, marginalia, consult stack. So I recommend it highly.

**Comment by morgandavidson** [comment]
Hi @mclearc thank you for the tip. I'll try embark. Nothing to do with this thread, but I'll take the opportunity to ask. Protesiloas Stavrou published [consult-denote](https://github.com/protesilaos/consult-denote) package I was wondering if it was an alternative to consult-note.

**Comment by mclearc** [comment]
@morgandavidson -- I haven't looked at his code very closely, so I'm mostly going off the description. But it sounds like it differs from consult-notes in being (i) denote only; (ii) more stringent in its adherence to the full denote filename. Consult notes reorganizes the info a bit and I suspect he didn't really want that. But I also don't know if that warranted a whole new package 🤷

**Comment by morgandavidson** [comment]
@mclearc Thank you, also I think that consult-notes has more functionalities.

I installed embark, but I have some issues when using it with consult-notes. When I open multiple (for example 7) org files I have to wait 30 seconds for them to open.

When I do the same using consult, it's instantaneous.

Here is my embark config:

```el
  (use-package embark
    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ("C-;" . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'
    :config
    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none))))
    )
  (use-package embark-consult
    :hook (embark-collect-mode . consult-preview-at-point-mode)
    )

```

**Comment by morgandavidson** [comment]
Hi @mclearc  -- Yes I confirm that consult will open the same 7 org files via Embark instantaneously.

**Comment by mclearc** [comment]
thanks @morgandavidson  -- I've opened a separate issue. Not sure what the problem is but I'll see what I can do. If there are other specifics that you have found concerning the slow response (e.g. org files only? Or other formats?), could you post them in that [issue thread](https://github.com/mclear-tools/consult-notes/issues/73)?
