### ISSUE TITLE
consult-notes-search-in-all-notes throws error

### ISSUE THREAD

**Issue by poulpoulsen** [mclear-tools/consult-notes#8]
hello,
after call the command this error occur.
i do not use org-roam.
is your package depending on it?

regards
poul

`
Debugger entered--Lisp error: (void-variable org-roam-directory)
  (expand-file-name org-roam-directory)
  (let* ((sources (mapcar 'expand-file-name (flatten-tree (mapcar 'cddr consult-notes-sources)))) (dirs (combine-and-quote-strings sources)) (roam (expand-file-name org-roam-directory)) (consult-grep-args (concat consult-notes-grep-args " " dirs " " (if consult-notes-org-roam-mode (progn roam)))) (consult-ripgrep-args (concat consult-notes-ripgrep-args " " dirs " " (if consult-notes-org-roam-mode (progn roam))))) (if consult-notes-use-rg (consult-ripgrep) (consult-grep)))
  consult-notes-search-in-all-notes()
  funcall-interactively(consult-notes-search-in-all-notes)
  call-interactively(consult-notes-search-in-all-notes record nil)
  command-execute(consult-notes-search-in-all-notes record)
  execute-extended-command(nil "consult-notes-search-in-all-notes" nil)
  funcall-interactively(execute-extended-command nil "consult-notes-search-in-all-notes" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by mclearc** [comment]
@poulpoulsen - please let me know if that fixes it.

**Comment by poulpoulsen** [comment]
hello again,
unfortunately not.
here is the debug output:
`
Debugger entered--Lisp error: (void-variable consult-notes-org-roam-mode)
  (if consult-notes-org-roam-mode (progn (expand-file-name org-roam-directory)))
  (concat consult-notes-grep-args " " dirs " " (if consult-notes-org-roam-mode (progn (expand-file-name org-roam-directory))))
  (let* ((sources (mapcar 'expand-file-name (flatten-tree (mapcar 'cddr consult-notes-sources)))) (dirs (combine-and-quote-strings sources)) (consult-grep-args (concat consult-notes-grep-args " " dirs " " (if consult-notes-org-roam-mode (progn (expand-file-name org-roam-directory))))) (consult-ripgrep-args (concat consult-notes-ripgrep-args " " dirs " " (if consult-notes-org-roam-mode (progn (expand-file-name org-roam-directory)))))) (if consult-notes-use-rg (consult-ripgrep) (consult-grep)))
  consult-notes-search-in-all-notes()
  funcall-interactively(consult-notes-search-in-all-notes)
  call-interactively(consult-notes-search-in-all-notes record nil)
  command-execute(consult-notes-search-in-all-notes record)
  execute-extended-command(nil "consult-notes-search-in-all-notes" nil)
  funcall-interactively(execute-extended-command nil "consult-notes-search-in-all-notes" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by mclearc** [comment]
@poulpoulsen -- looks like the var `consult-notes-org-roam-mode` just needs to be defined. See if the latest commit helps then.

**Comment by mclearc** [comment]
When running `emacs -Q` I'm not seeing any issues with `consult-notes-search-in-all-notes`. Here's the setup I used:

```emacs-lisp
(use-package consult
  :straight (consult :type git :host github :repo "minad/consult" :includes consult-org))

(customize-set-variable 'lem-notes-dir (concat (getenv "HOME") "/Documents/notes/"))
(use-package consult-notes
  :straight (:local-repo "/Users/roambot/bin/lisp-projects/consult-notes")
  :commands (consult-notes consult-notes-search-in-all-notes)
  :config
  (setq consult-notes-sources
        `(("Zettel"          ?z ,(concat lem-notes-dir "zettel/"))
          ("Lecture Notes"   ?l ,(concat lem-notes-dir "lecture-notes/"))
          ("Reference Notes" ?r ,(concat lem-notes-dir "ref-notes/"))
          ("Org"             ?o "~/Dropbox/org-files/")
          ("Workbook"        ?w ,(concat lem-notes-dir "workbook/"))
          ("Refile"          ?R ,(concat lem-notes-dir "refile-notes/")))))
```

Could you perhaps show me the config for consult-notes that you're using?

**Comment by poulpoulsen** [comment]
this is my config:
(add-to-list 'load-path "~/.emacs.d/contrib-lisp/consult-notes")
(require 'consult-notes)
(setq consult-notes-sources
      `(("denote"  ?d ,denote-directory)
        ))`
`
i'm on emacs 29 Linux fedora35

**Comment by poulpoulsen** [comment]
i found a fix.
(setq consult-notes-org-roam-mode nil) 
and it works
so i think, that the check for org-roam is not correct.

**Comment by mclearc** [comment]
Yes exactly. Once I get that fixed I'll let you know. But in the meantime glad that works for you.

**Comment by poulpoulsen** [comment]
ok thanks

**Comment by mclearc** [comment]
@poulpoulsen the minor mode is now set to an initial value of nil so you shouldn't have to set this yourself.

**Comment by mclearc** [comment]
@poulpoulsen are you still seeing any errors?

**Comment by poulpoulsen** [comment]
Hello,
with your latest updates it is OK here.
Thank you for your effort
regards
Poul

----------------------------------------

Von: Colin McLear ***@***.***>
An: mclear-tools/consult-notes ***@***.***>
Kopie: poulpoulsen ***@***.***>; Mention 
***@***.***>
Datum: 13.08.2022 23:11:27
Betreff: Re: [mclear-tools/consult-notes] 
consult-notes-search-in-all-notes throws error (Issue #8)
